"""Compare the package against small reference curves generated by MS-S."""
from pathlib import Path

import numpy as np
import pytest

from lambda_support_recovery import compute_support_curve, select_from_curve


@pytest.mark.parametrize("name,omega_ref,fit_omega_ref,refine,scope", [
    ("estimated", None, True, False, "upper"),
    ("known", 0.4, False, False, "upper"),
    ("free", None, False, False, "upper"),
    ("refined", 0.4, False, True, "upper"),
    ("directed", None, True, False, "all"),
])
def test_objectives_and_model_masks_match_ms_s(name, omega_ref, fit_omega_ref, refine, scope):
    with np.load(Path(__file__).parent / "fixtures" / (name + ".npz")) as reference:
        curve = compute_support_curve(
            reference["sigma"], num_samples=1000, max_restarts=2, max_iter=120,
            omega_ref=omega_ref, fit_omega_ref=fit_omega_ref,
            refine_after_fixed_omega=refine, support_scope=scope,
        )
        np.testing.assert_array_equal(curve.dimensions, reference["dimensions"])
        np.testing.assert_allclose(curve.raw_objectives, reference["objectives"], rtol=1e-11, atol=1e-12)
        np.testing.assert_array_equal(curve.support_masks, reference["masks"])
        np.testing.assert_array_equal(curve.support_valid, reference["valid"])
        if name == "estimated":
            ordinary = select_from_curve(curve, method="plateau", return_result=True)
            np.testing.assert_allclose(ordinary.penalty_values, reference["weighted_penalties"], rtol=1e-12)
            assert ordinary.selected_dimension == int(reference["plateau_dimension"])
            bootstrap = select_from_curve(curve, bootstrap_replicates=19, return_result=True)
            np.testing.assert_allclose(bootstrap.penalty_values, reference["penalties"], rtol=1e-12)
            assert bootstrap.selected_dimension == int(reference["bootstrap_dimension"])
            np.testing.assert_array_equal(bootstrap.diagnostics.candidate_dimensions, reference["bootstrap_candidates"])
            np.testing.assert_array_equal([c.p_value for c in bootstrap.bootstrap_comparisons], reference["bootstrap_p_values"])
            np.testing.assert_allclose([c.bootstrap_gains for c in bootstrap.bootstrap_comparisons], reference["bootstrap_gains"], rtol=1e-11, atol=1e-12)
